<?php
if (!defined('ABSPATH')) {
    exit;
}

/**
 * The "ChatWP Widget" — each instance picks its own LLM provider, model,
 * and prompt, and displays the generated text on render.
 */
class ChatWP_Widget extends WP_Widget
{
    public function __construct()
    {
        parent::__construct(
            'chatwp_widget',
            'ChatWP Widget',
            array('description' => __('Displays text generated by an LLM (OpenAI, Anthropic, or a local/open source model).', 'chatwp'))
        );
    }

    public function widget($args, $instance)
    {
        $title = apply_filters('widget_title', isset($instance['title']) ? $instance['title'] : '');
        $provider_key = !empty($instance['provider']) ? $instance['provider'] : 'openai';

        $provider = ChatWP_Provider_Factory::create($provider_key);
        $result = $provider->generate(array(
            'prompt' => isset($instance['prompt']) ? $instance['prompt'] : '',
            'system_prompt' => isset($instance['system_prompt']) ? $instance['system_prompt'] : '',
            'model' => isset($instance['model']) ? $instance['model'] : '',
            'temperature' => isset($instance['temperature']) ? $instance['temperature'] : 0.9,
            'max_tokens' => isset($instance['max_tokens']) ? $instance['max_tokens'] : 250,
            'frequency_penalty' => isset($instance['frequency_penalty']) ? $instance['frequency_penalty'] : '',
            'presence_penalty' => isset($instance['presence_penalty']) ? $instance['presence_penalty'] : '',
        ));

        $text = '';
        if (is_wp_error($result)) {
            // Don't leak API error details to anonymous visitors; admins see them to aid debugging.
            if (current_user_can('manage_options')) {
                $text = '<em>ChatWP error: ' . esc_html($result->get_error_message()) . '</em>';
            }
        } else {
            $text = wp_kses_post($result);
        }

        echo $args['before_widget'];
        if (!empty($title)) {
            echo $args['before_title'] . $title . $args['after_title'];
        }
        echo '<div class="chatwp-text">' . $text . '</div>';
        echo $args['after_widget'];
    }

    public function form($instance)
    {
        $title = isset($instance['title']) ? $instance['title'] : '';
        $provider_key = isset($instance['provider']) ? $instance['provider'] : 'openai';
        $model = isset($instance['model']) ? $instance['model'] : 'gpt-4o-mini';
        $system_prompt = isset($instance['system_prompt']) ? $instance['system_prompt'] : '';
        $prompt = isset($instance['prompt']) ? $instance['prompt'] : 'How many owls does it take to get to the center of a sparrow nest?';
        $temperature = isset($instance['temperature']) ? $instance['temperature'] : '0.9';
        $max_tokens = isset($instance['max_tokens']) ? $instance['max_tokens'] : '250';
        $frequency_penalty = isset($instance['frequency_penalty']) ? $instance['frequency_penalty'] : '0';
        $presence_penalty = isset($instance['presence_penalty']) ? $instance['presence_penalty'] : '0.6';
        $providers = ChatWP_Provider_Factory::get_providers();
?>
        <div class="chatwp-widget-form">
            <p>
                <label for="<?php echo esc_attr($this->get_field_id('title')); ?>"><?php esc_html_e('Title:', 'chatwp'); ?></label>
                <input class="widefat" id="<?php echo esc_attr($this->get_field_id('title')); ?>" name="<?php echo esc_attr($this->get_field_name('title')); ?>" type="text" value="<?php echo esc_attr($title); ?>">
            </p>
            <p>
                <label for="<?php echo esc_attr($this->get_field_id('provider')); ?>"><?php esc_html_e('LLM Provider:', 'chatwp'); ?></label>
                <select class="widefat chatwp-provider-select" id="<?php echo esc_attr($this->get_field_id('provider')); ?>" name="<?php echo esc_attr($this->get_field_name('provider')); ?>">
                    <?php foreach ($providers as $key => $label) : ?>
                        <option value="<?php echo esc_attr($key); ?>" <?php selected($provider_key, $key); ?>><?php echo esc_html($label); ?></option>
                    <?php endforeach; ?>
                </select>
            </p>
            <p>
                <label for="<?php echo esc_attr($this->get_field_id('model')); ?>"><?php esc_html_e('Model:', 'chatwp'); ?></label>
                <input class="widefat" id="<?php echo esc_attr($this->get_field_id('model')); ?>" name="<?php echo esc_attr($this->get_field_name('model')); ?>" type="text" value="<?php echo esc_attr($model); ?>">
                <span class="description chatwp-model-hint" data-provider="openai">e.g. gpt-4o-mini, gpt-4o</span>
                <span class="description chatwp-model-hint" data-provider="anthropic">e.g. claude-sonnet-4-5, claude-haiku-4-5</span>
                <span class="description chatwp-model-hint" data-provider="ollama">e.g. llama3.1, mistral, qwen2.5</span>
                <span class="description chatwp-model-hint" data-provider="custom"><?php esc_html_e('Model name as recognized by your custom endpoint.', 'chatwp'); ?></span>
            </p>
            <p>
                <label for="<?php echo esc_attr($this->get_field_id('system_prompt')); ?>"><?php esc_html_e('System Prompt (optional):', 'chatwp'); ?></label>
                <textarea class="widefat" rows="2" id="<?php echo esc_attr($this->get_field_id('system_prompt')); ?>" name="<?php echo esc_attr($this->get_field_name('system_prompt')); ?>"><?php echo esc_textarea($system_prompt); ?></textarea>
            </p>
            <p>
                <label for="<?php echo esc_attr($this->get_field_id('prompt')); ?>"><?php esc_html_e('Prompt:', 'chatwp'); ?></label>
                <input class="widefat" id="<?php echo esc_attr($this->get_field_id('prompt')); ?>" name="<?php echo esc_attr($this->get_field_name('prompt')); ?>" type="text" value="<?php echo esc_attr($prompt); ?>">
            </p>
            <p>
                <label for="<?php echo esc_attr($this->get_field_id('temperature')); ?>"><?php esc_html_e('Temperature:', 'chatwp'); ?></label>
                <input class="widefat" id="<?php echo esc_attr($this->get_field_id('temperature')); ?>" name="<?php echo esc_attr($this->get_field_name('temperature')); ?>" type="text" value="<?php echo esc_attr($temperature); ?>">
            </p>
            <p>
                <label for="<?php echo esc_attr($this->get_field_id('max_tokens')); ?>"><?php esc_html_e('Max Tokens:', 'chatwp'); ?></label>
                <input class="widefat" id="<?php echo esc_attr($this->get_field_id('max_tokens')); ?>" name="<?php echo esc_attr($this->get_field_name('max_tokens')); ?>" type="text" value="<?php echo esc_attr($max_tokens); ?>">
            </p>
            <p class="chatwp-provider-only" data-providers="openai,custom">
                <label for="<?php echo esc_attr($this->get_field_id('frequency_penalty')); ?>"><?php esc_html_e('Frequency Penalty:', 'chatwp'); ?></label>
                <input class="widefat" id="<?php echo esc_attr($this->get_field_id('frequency_penalty')); ?>" name="<?php echo esc_attr($this->get_field_name('frequency_penalty')); ?>" type="text" value="<?php echo esc_attr($frequency_penalty); ?>">
            </p>
            <p class="chatwp-provider-only" data-providers="openai,custom">
                <label for="<?php echo esc_attr($this->get_field_id('presence_penalty')); ?>"><?php esc_html_e('Presence Penalty:', 'chatwp'); ?></label>
                <input class="widefat" id="<?php echo esc_attr($this->get_field_id('presence_penalty')); ?>" name="<?php echo esc_attr($this->get_field_name('presence_penalty')); ?>" type="text" value="<?php echo esc_attr($presence_penalty); ?>">
            </p>
        </div>
    <?php
    }

    public function update($new_instance, $old_instance)
    {
        $valid_providers = array_keys(ChatWP_Provider_Factory::get_providers());

        $instance = array();
        $instance['title'] = (!empty($new_instance['title'])) ? sanitize_text_field($new_instance['title']) : '';
        $instance['provider'] = (!empty($new_instance['provider']) && in_array($new_instance['provider'], $valid_providers, true))
            ? $new_instance['provider']
            : 'openai';
        $instance['model'] = (!empty($new_instance['model'])) ? sanitize_text_field($new_instance['model']) : '';
        $instance['system_prompt'] = (!empty($new_instance['system_prompt'])) ? sanitize_textarea_field($new_instance['system_prompt']) : '';
        $instance['prompt'] = (!empty($new_instance['prompt'])) ? sanitize_text_field($new_instance['prompt']) : '';
        $instance['temperature'] = (!empty($new_instance['temperature'])) ? sanitize_text_field($new_instance['temperature']) : '';
        $instance['max_tokens'] = (!empty($new_instance['max_tokens'])) ? sanitize_text_field($new_instance['max_tokens']) : '';
        $instance['frequency_penalty'] = (!empty($new_instance['frequency_penalty'])) ? sanitize_text_field($new_instance['frequency_penalty']) : '';
        $instance['presence_penalty'] = (!empty($new_instance['presence_penalty'])) ? sanitize_text_field($new_instance['presence_penalty']) : '';
        return $instance;
    }
}
